// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MantenimientoGrupoGB.EN.Model
{
    public partial class UsuarioBase
    {
        [Key]
        public Guid IdUsuario { get; set; }
        [Required]
        [StringLength(100)]
        public string Nombres { get; set; }
        [Required]
        [StringLength(100)]
        public string Apellidos { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime FechaNacimiento { get; set; }
        [Required]
        [Column("DUI")]
        [StringLength(9)]
        public string Dui { get; set; }
        [Required]
        [Column("NIT")]
        [StringLength(14)]
        public string Nit { get; set; }
        [Required]
        [Column("ISSS")]
        [StringLength(10)]
        public string Isss { get; set; }
        [Required]
        [StringLength(12)]
        public string Telefono { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime FechaCreacion { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? FechaModificacion { get; set; }
        public bool EstadoEliminado { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? FechaEliminacion { get; set; }
    }
}